### ISSUE TITLE
关于登录功能说明

### ISSUE THREAD

**Issue by VectorZhao** [Dogtiti/AutoGPT-Next-Web#117]
NEXTAUTH_URL=http://localhost:3000
DATABASE_URL=file:./db.sqlite

这两个参数没搞懂是什么意思。
我想使用数据库功能。

**Comment by Dogtiti** [comment]
这个建议先看看代码 
得有一定理解才知道怎么弄，目前还没有计划去支持这块的文档
关键词`prisma` `next/auth`

**Comment by VectorZhao** [comment]
这个功能就是agentgpt那个demo的登录功能吧，这个项目取消了？右侧一直这样。执行完一个agent之后依然如此。
![image](https://user-images.githubusercontent.com/16644993/236409428-f86b98a6-9ac1-49ca-aa0e-0e8ceb089ced.png)

**Comment by Dogtiti** [comment]
不知道你指的是什么功能，登录功能一直是有的，需要自己去集成，一键部署不包括登录，登录需要服务器相关的东西。
我们主站也是有登录的，都是本项目一套代码，可以自己看看代码实现

**Comment by VectorZhao** [comment]
左上角的这些文字，无论怎么操作始终会显示。
agentgpt我试了，不配置prisma，一样可以显示谷歌，github等登录按钮，只不过登不了。

**Comment by Dogtiti** [comment]
正是因为登不了所以就屏蔽了 ，左上角的文字只是告诉你目前是一个非登录模式 只能单例运行无法保存 ，晚点我优化一下这个文案把

**Comment by Dogtiti** [comment]
一键部署的目的就是让你低成本快速的使用，所以会处理掉一些不需要的功能，如果放一个登录按钮 你又用不了，那没什么意义，如果你确实想实现自己的登录功能，可以先看看代码，有问题可以在这个issue里留言，我看到了就会回复你

**Comment by Dogtiti** [comment]
大致给你说一下实现步骤：

- 需要一台服务器（serverless最方便），配置mysql数据库
- 申请包括但不限于Google,Github等client id , client secret(OAuth)
- 按需填入对应的环境变量

复杂的是前两步，后面就是配置问题了

**Comment by VectorZhao** [comment]
好的，谢谢。我部署在了国外vps上，
docker-compose文件配置如下：
```
version: '3'

services:
  myapp:
    container_name: agent-gpt
    image: vectorzhao/agent-gpt
    environment:
      NODE_ENV: development
      NEXTAUTH_SECRET: '1234'
      NEXTAUTH_URL: 'https://agexxxxxxxx'
      DATABASE_URL: file:./db.sqlite
      OPENAI_API_KEY: 'sk-xxxxxxxx'
    ports:
      - "23000:3000"
    volumes:
      - ./db.sqlite:/app/db.sqlite # 将 SQLite 数据库文件夹映射至容器内

  prisma:
    container_name: prisma
    image: prismagraphql/prisma:1.34
    command: ["migrate", "deploy"]
    volumes:
      - ./prisma:/app/prisma
      - ./db.sqlite:/app/db.sqlite # 映射 SQLite 数据库文件夹
    environment:
      DATABASE_URL: file:./db.sqlite # 使用相同的数据库连接URL

volumes:
  app-data:
```

docker 的日志如下：
```
Prisma schema loaded from prisma/schema.prisma

✔ Generated Prisma Client (4.13.0 | library) to ./node_modules/@prisma/client in 2.80s
You can now start using Prisma Client in your code. Reference: https://pris.ly/d/client

import { PrismaClient } from '@prisma/client'
const prisma = new PrismaClient()

Prisma schema loaded from prisma/schema.prisma
Datasource "db": SQLite database "db.sqlite" at "file:./db.sqlite"

SQLite database db.sqlite created at file:./db.sqlite

Applying migration `20230505081334_init`

The following migration(s) have been created and applied from new schema changes:

migrations/
  └─ 20230505081334_init/
    └─ migration.sql

Your database is now in sync with your schema.

✔ Generated Prisma Client (4.13.0 | library) to ./node_modules/@prisma/client in
 1.21s


Prisma schema loaded from prisma/schema.prisma
Datasource "db": SQLite database "db.sqlite" at "file:./db.sqlite"

The database is already in sync with the Prisma schema.

✔ Generated Prisma Client (4.13.0 | library) to ./node_modules/@prisma/client in
 1.22s


> auto-gpt-next-web@1.0.0 start
> next start

warn  - You are using a non-standard "NODE_ENV" value in your environment. This creates inconsistencies in the project and is strongly advised against. Read more: https://nextjs.org/docs/messages/non-standard-node-env
ready - started server on 0.0.0.0:3000, url: http://localhost:3000

```

对于你说的实现步骤，，，，，毫无头绪。纯小白。。。。。
