### ISSUE TITLE
求支持proxy_url配置

### ISSUE THREAD

**Issue by haiker666** [Dogtiti/AutoGPT-Next-Web#37]
求支持proxy_url配置
因为有搭建在境内的需求，但是openai境内不可访问

**Comment by lloydzhou** [comment]
1. local模式运行的时候，使用npm 启动项目之前设置https_proxy环境变量
```
https_proxy=xxxx npm run dev
```
2. 如果是docker启动的也是可以直接配置环境变量
```
docker run -d --env HTTPS_PROXY="sock5://xxxxx:xxx" --name agentgpt -p 3000:3000 -v $(pwd)/db:/app/db agentgpt
```
4. 使用docker-compose运行，也是一样的在配置文件里面写上环境变量
```
version: "3.0"
services:
  autogpt:
    // .....省略其他，配置代理
    environment:
      - HTTPS_PROXY=xxxx

```
